knp_paginator:
    page_range: 5                       # Number of page links to show
    default_options:
        page_name: page                 # Page parameter name
        sort_field_name: sort           # Sort field parameter name
        sort_direction_name: direction  # Sort direction parameter name
        distinct: true                  # Ensure distinct results
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_sortable_link.html.twig'
